Add checks for certain variables in veJOE staking
traderjoe-xyz/joe-core pull request #40
Opened 2022-02-12 18:47 UTC by 0xnivek

This PR adds checks to enforce:

- `boostedThreshold > 0`
- `boostedDuration <= 365 days`
- `maxCap <= 100000`

and also adds tests

2022-02-12 19:50 UTC, LouisMeMyself commented on contracts/VeJoeStaking.sol
> +    uint256 public MAX_MAX_CAP;
I don’t think this is a good name for a variable..
Maybe `UPPER_BOUND_MAX_CAP` or `UPPER_LIMIT_MAX_CAP` ?

2022-02-12 19:51 UTC, LouisMeMyself commented on contracts/VeJoeStaking.sol
> +    uint256 public MAX_BOOSTED_DURATION;
If we change the name for the previous upper bound, we should rename this too

2022-02-12 23:00 UTC, jummy123 commented on contracts/VeJoeStaking.sol
> +    uint256 public UPPER_LIMIT_BOOSTED_DURATION;
One of the feedback I have received before is not to name these variables in UPPERCASE_WITH_UNDERSCORES as they aren't actually `immutable` variables.

2022-02-12 23:02 UTC, jummy123 commented on contracts/VeJoeStaking.sol
> +        UPPER_LIMIT_BOOSTED_DURATION = 365 days;
Optional, you can define this just before the `require` statements where they are used, saving gas on failed txs.

2022-02-13 01:18 UTC, cryptofish7 requested changes

2022-02-13 01:18 UTC, cryptofish7 commented on contracts/VeJoeStaking.sol
> +        UPPER_LIMIT_MAX_CAP = 100000;
Can we define `UPPER_LIMIT_MAX_CAP`, `UPPER_LIMIT_BOOSTED_DURATION` and `PRECISION` as immutable variables and assign them in a constructor instead?

Or, we don't use upper snake case.

2022-02-13 01:29 UTC, cryptofish7 approved these changes

2022-02-13 01:29 UTC, merged